// <auto-generated />
using System;
using Data.DataConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.DataConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201118121138_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Data.Models.Models.Manufacturer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = "583ce722-1eaf-4eb7-9d9a-ed79f00fc498",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 265, DateTimeKind.Local).AddTicks(8086),
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentCountInWarehouse")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManufacturerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MinimumCountAlert")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 269, DateTimeKind.Local).AddTicks(7609),
                            CurrentCountInWarehouse = 10,
                            ManufacturerId = "583ce722-1eaf-4eb7-9d9a-ed79f00fc498",
                            MinimumCountAlert = 10,
                            ProductName = "Ball",
                            ProductPrice = 1m
                        },
                        new
                        {
                            Id = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 269, DateTimeKind.Local).AddTicks(8408),
                            CurrentCountInWarehouse = 10,
                            ManufacturerId = "583ce722-1eaf-4eb7-9d9a-ed79f00fc498",
                            MinimumCountAlert = 10,
                            ProductName = "Bat",
                            ProductPrice = 11m
                        },
                        new
                        {
                            Id = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 269, DateTimeKind.Local).AddTicks(8441),
                            CurrentCountInWarehouse = 10,
                            ManufacturerId = "583ce722-1eaf-4eb7-9d9a-ed79f00fc498",
                            MinimumCountAlert = 10,
                            ProductName = "Bike",
                            ProductPrice = 100m
                        },
                        new
                        {
                            Id = "8db046cf-1750-4f36-9135-404376828bc6",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 269, DateTimeKind.Local).AddTicks(8555),
                            CurrentCountInWarehouse = 10,
                            ManufacturerId = "583ce722-1eaf-4eb7-9d9a-ed79f00fc498",
                            MinimumCountAlert = 10,
                            ProductName = "T-shirt",
                            ProductPrice = 15m
                        });
                });

            modelBuilder.Entity("Data.Models.Models.Seller", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerNumber = "1",
                            UserId = "45c402ff-a837-401f-a76f-0b73b32ce8f0"
                        },
                        new
                        {
                            Id = "774f0285-2ecd-4c3f-a323-75d616faa451",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerNumber = "2",
                            UserId = "2aed7b9d-7c7b-4b75-8303-2fc29044c5dc"
                        },
                        new
                        {
                            Id = "57efa730-5816-434d-9b5a-004de3cec24a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerNumber = "3",
                            UserId = "e0846e07-e605-40c6-9e04-45a1969160dd"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.SellerCustomer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("SellerCustomers");
                });

            modelBuilder.Entity("Data.Models.Models.SellerProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("SellerProduct");

                    b.HasData(
                        new
                        {
                            Id = "d10891c0-bc4a-4610-9687-baaeb7c91f4f",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(243),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "473a8af3-0d5c-4581-9acd-e93e0f60a3b9",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(344),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "f6534118-82a9-4462-821e-2ad781a9a6bd",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(375),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "0f984c8f-30bd-48d4-8c26-094829046671",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(405),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "0793986c-8908-4944-9bc0-1692c7b8a05b",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(441),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "b406d86c-508e-4c04-94be-01f20cfa4bc5",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(475),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "17849698-bd09-481e-9a41-c55e22bbe4ef",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(504),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "af5e6814-b488-4f17-bacd-37eb18da7cb9",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(534),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "3dfae65b-c4ae-4803-8803-acce577a0a21",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(567),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "dfb782f3-fecc-4a75-a18f-e6afafcf3528",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(598),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "4dab7cb9-395c-4fd3-ba9f-72b16cecb63c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(628),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "4a2c8555-9b0a-492d-b6f1-d0cdb0592198",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(656),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "3099dd40-f33c-4774-a7dd-719e4b15f385",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(687),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "ea9a8588-fd6b-4995-bde3-d5484c08d5ce",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(763),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "9f1a90fd-07ab-4caf-b33f-9088b6ecc89d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(792),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "7503ce66-3417-4715-b6b8-87720b6e5d79",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(819),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "bd61481c-2ad1-4e5d-afb2-37d80ed2faaa",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(850),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "2f969a82-540f-4930-8bf8-b3dac879a23d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(881),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "a30dcb27-0d2a-429c-bc5b-4c72626136c4",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(910),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "f1dd098a-6720-4dab-8da9-aba4ec54be36",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(939),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "2711c625-7f59-439b-ae86-c42ff2210da5",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(971),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "09ec9dbd-7945-4bbe-a339-c533f4096b6c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(999),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "e835e035-3731-48c6-bf8c-01fe35418408",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1027),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "3fb7355e-9174-471d-975e-689b27225023",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1054),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "be8de00f-d765-4cb5-b62b-a7cbec142704",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1086),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "d949cb9e-3e40-4720-9a89-2c42b6ff2f12",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1116),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "9868bb79-9865-4b51-a78a-03a8183241bd",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1144),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "c55212a7-d382-4158-8f71-e5c183a99d65",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1213),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "09f29185-54d0-48ce-b07d-0ee64737c73c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1244),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "fcd22986-ae2d-4bae-ac74-624ff763ad07",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1274),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "3a9c2262-1cfb-4299-b074-16b09f451f52",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1303),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "d7a9db5e-11cc-4c17-a874-d19e36583122",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1333),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "0d82ba6c-b070-4f61-81f1-efac28096f8e",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1365),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "17f53e78-7ade-4ed5-89a5-67ce00f5e642",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1397),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "8b76f5ba-ca02-49bb-bc8c-f66dca8593f3",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1427),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "b0737563-b8dd-4371-8922-db29aa28276c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1456),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "899033c8-83f2-45cc-b561-db06339e0850",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1486),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "b2e359d8-0514-48e2-a091-fa0cd9c43b36",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1515),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "8d8a3c3e-8f2e-4ab0-99b7-cf460ee1aaae",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1543),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "93affad1-cccd-483f-9ad4-365d45c09bc1",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1571),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "58b652e2-97d9-4dab-b214-871c1293e8e7",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1645),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "c60bfce4-d74a-4841-b974-284a5dde9904",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1673),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "b06bff1b-90ff-4bab-a563-4f788837847c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1704),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "a365318b-a87a-46df-a48b-0e6c0cec6686",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1733),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "f9cf0374-b2c2-4efb-bdd5-ce69cbde4a44",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1765),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "f959fa5b-6a43-47c3-9afa-752bd4a20800",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1793),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "d7aaddc0-66f7-4280-8427-2657315d3d67",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1822),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "587ac3e6-dd95-4787-b8a1-190639ca70ca",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1851),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "623a2901-1fa7-418b-aa91-b30294bf8ff6",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1883),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "6ee9aefa-3d21-4033-82c1-9f9820efe014",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1911),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "23703c4e-c91d-46f2-9742-c2adab9e332d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1939),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "d9e578d5-3ea3-42f9-a61e-04fc78bd29ea",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1967),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "a8e00c9a-fe66-4036-a24d-a5452f9bda6a",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(1997),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "ad03df5c-6030-4c69-b28f-92313caf1050",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2026),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "4427b088-d616-4c97-a790-a39e7859e70c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2129),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "ec84d9e6-bc86-4900-8668-9c2e6263eb14",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2159),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "3bf47206-3b91-43bf-a7e6-19f83d3d94ff",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2189),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "94dfc0cd-7622-424a-8c68-c670d1a421b3",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2218),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "98f678c2-0f9f-491a-b864-fb720bbbb525",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2247),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "c8dca0e9-b42a-40c0-b807-c34e54c2808d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2275),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "68e43b0d-b264-4fd2-b7f5-2d6dfe2203a5",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2306),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "be72bfed-940f-4d5b-9004-8ba9656c0578",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2335),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "68db73cc-f323-4bbe-ab60-98699659ac93",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2363),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "f02de763-5779-4f73-9bd8-ddc89b117198",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2391),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "9edaf118-b07b-44d0-8299-e4576f3a53f2",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2422),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "ed9ebd01-c0ca-4242-898b-2e2f6d72a25b",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2450),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "68f03add-62d7-427c-8948-865dc7736795",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2479),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "3083144c-7688-4476-96b6-9badeb2ed5e8",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2546),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "833453b3-efa3-41f4-9756-d419c20dd638",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2575),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "bd851f7f-3635-470d-8bb6-b7bd52b4b33e",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2603),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "be1c46c9-156a-4dde-a272-5b4c0eacfd8d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2632),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "fcdb8874-71bd-41a4-814e-5a3469ba59da",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2660),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "87b252f8-51b9-49aa-88d5-336111b64fa9",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2692),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "c34c8706-8962-4f03-b622-3e574baa5554",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2718),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "a15a6135-3170-4491-ad7d-d210a9ee1223",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2747),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "2be6addb-ec77-4519-baa8-c5f3fa59648d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2774),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "2ac920bc-782a-49f7-862c-e7c086719ff4",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2804),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "aff28b3c-a433-4a75-a2a4-606c70df8307",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2833),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "da115d83-6444-48fc-b643-80828a5e90ed",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2861),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "7acc83c9-3efe-4f69-b0ea-a1af1483ded5",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2890),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "28d532bf-7e67-43fb-879a-4dbafbddc669",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2920),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "4e82b2b6-d51e-4048-80b9-886081c72919",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(2988),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "87ec9ae2-8a42-4dd1-b907-0ebbc079862c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3016),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "8c049110-c185-424c-9ce3-0640c563c07c",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3044),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "6c646884-7fb1-4976-8d9d-516853c41a6a",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3075),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "1f52506c-95a1-4ca5-bce7-3d27cb17011f",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3104),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "1bc352d1-c2c1-44b6-9a11-5094d91213bf",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3131),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "c4fe7c0a-21be-4da9-92aa-a7ce050f7cde",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3159),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "58ec80a4-272a-46ef-af95-4e8f49e0cfb3",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3190),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "1478b4af-930a-46f4-a34b-80db129945ab",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3217),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "559e229f-13c6-46c9-80a1-84eaa00f83cd",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3243),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "c9481f94-5d72-4fd7-a169-8c5a93b9105a",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3270),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "29323d59-e151-4460-9b87-b388b116798f",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3299),
                            ProductId = "98810ec2-b859-4f8d-8558-e991722bc92b",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "645f6a55-ed53-49c6-be8d-86f6f9353047",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3326),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "ac1159e2-d8de-4d34-a0c7-9a2e8bd823ce"
                        },
                        new
                        {
                            Id = "cbeb668f-024c-4a42-8cfb-77c4ffbcad42",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3354),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "5fde1b58-69f8-4d19-a81b-c1d528e9d25d",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3381),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "48cc3b5b-12a1-4d63-a599-764a2df09751",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3451),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "42a0b6b1-d99d-45e4-9928-b7791c67fbf9",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3479),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "8fd6ae81-277b-4452-ae86-8b218e3be9d1",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3505),
                            ProductId = "62719331-2b9d-4880-a12e-3f123b03e8ec",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        },
                        new
                        {
                            Id = "d46db939-6b16-4844-a5e9-7c33f35fa259",
                            CreatedAt = new DateTime(2020, 11, 18, 14, 11, 38, 270, DateTimeKind.Local).AddTicks(3533),
                            ProductId = "7e985d13-c0b7-4685-b449-a03e5c7c3f49",
                            SellerId = "774f0285-2ecd-4c3f-a323-75d616faa451"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "45c402ff-a837-401f-a76f-0b73b32ce8f0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            UserName = "Minka"
                        },
                        new
                        {
                            Id = "2aed7b9d-7c7b-4b75-8303-2fc29044c5dc",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            UserName = "Pesho"
                        },
                        new
                        {
                            Id = "e0846e07-e605-40c6-9e04-45a1969160dd",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            UserName = "Gosho"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.Customer", b =>
                {
                    b.HasOne("Data.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.Models.Models.Product", b =>
                {
                    b.HasOne("Data.Models.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("Data.Models.Models.Seller", b =>
                {
                    b.HasOne("Data.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.Models.Models.SellerCustomer", b =>
                {
                    b.HasOne("Data.Models.Models.Customer", "Customer")
                        .WithMany("SellerCustomers")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Data.Models.Models.Product", null)
                        .WithMany("SellerCustomers")
                        .HasForeignKey("ProductId");

                    b.HasOne("Data.Models.Models.Seller", "Seller")
                        .WithMany("SellerCustomers")
                        .HasForeignKey("SellerId");
                });

            modelBuilder.Entity("Data.Models.Models.SellerProduct", b =>
                {
                    b.HasOne("Data.Models.Models.Product", "Product")
                        .WithMany("SellerProducts")
                        .HasForeignKey("ProductId");

                    b.HasOne("Data.Models.Models.Seller", "Seller")
                        .WithMany("SellerProducts")
                        .HasForeignKey("SellerId");
                });
#pragma warning restore 612, 618
        }
    }
}
