// <auto-generated />
using System;
using Data.DataConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.DataConnection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201119074757_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Data.Models.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Data.Models.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentCountInWarehouse")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinimumCountAlert")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "79991602-1a2d-4802-8382-49f06fe414ef",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "b7972",
                            ProductPrice = 0m
                        },
                        new
                        {
                            Id = "c922d9c3-b8f8-4c11-9516-bb042107f34d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "51458",
                            ProductPrice = 10m
                        },
                        new
                        {
                            Id = "b0836acc-acd3-4408-8af7-c1fe85ff3fcf",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "13d5c",
                            ProductPrice = 20m
                        },
                        new
                        {
                            Id = "95b059b5-9341-4b63-975e-0be2116ec68a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "d9d2b",
                            ProductPrice = 30m
                        },
                        new
                        {
                            Id = "664e9dc8-770e-4022-b222-eef3d6ed77ea",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "88090",
                            ProductPrice = 40m
                        },
                        new
                        {
                            Id = "c32459d5-cb0a-410c-abf3-1129dc40c4be",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "be7e0",
                            ProductPrice = 50m
                        },
                        new
                        {
                            Id = "66716477-cdc6-434a-9a7a-a47bc27748b4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "191b6",
                            ProductPrice = 60m
                        },
                        new
                        {
                            Id = "49e8c335-dcc9-4caf-a043-c5c3cf80bc72",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "aa277",
                            ProductPrice = 70m
                        },
                        new
                        {
                            Id = "370190e4-cf7b-4cb9-a5f8-e94ce111339a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "5a692",
                            ProductPrice = 80m
                        },
                        new
                        {
                            Id = "35afa419-73f9-41c1-9f4f-7c86e88b62c8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "a96ea",
                            ProductPrice = 90m
                        },
                        new
                        {
                            Id = "7ef5be5a-6033-4bac-b520-7e710a50a94a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "69fb1",
                            ProductPrice = 100m
                        },
                        new
                        {
                            Id = "03a70466-dc82-427d-97f0-38a4ba09cbde",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "4d885",
                            ProductPrice = 110m
                        },
                        new
                        {
                            Id = "9bdc4a8a-39cc-46ae-a29e-185aa6faeea8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "ebefe",
                            ProductPrice = 120m
                        },
                        new
                        {
                            Id = "55a010fd-d9aa-4152-b474-71434c259a9f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "a2529",
                            ProductPrice = 130m
                        },
                        new
                        {
                            Id = "db54676c-67f9-406d-93d6-21e269d5f233",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "9912c",
                            ProductPrice = 140m
                        },
                        new
                        {
                            Id = "b2d80bcd-e262-483b-a082-e2e6529c0d4f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "3c541",
                            ProductPrice = 150m
                        },
                        new
                        {
                            Id = "79956d3c-656e-4859-b569-ef2b710b58f1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "56351",
                            ProductPrice = 160m
                        },
                        new
                        {
                            Id = "0971f52f-f98e-4543-9174-5ab5236d3d3c",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "23516",
                            ProductPrice = 170m
                        },
                        new
                        {
                            Id = "ce8b8d60-9897-49c4-9056-59bba14fa6a0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "3e3d6",
                            ProductPrice = 180m
                        },
                        new
                        {
                            Id = "ec147189-3482-4f78-9dae-d274feef8bf9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "c654d",
                            ProductPrice = 190m
                        },
                        new
                        {
                            Id = "f05f0c78-c569-48fe-95af-5f5af7b4f751",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "fd897",
                            ProductPrice = 200m
                        },
                        new
                        {
                            Id = "3f79d0ef-69bf-499b-8c25-619629394e84",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "5c8da",
                            ProductPrice = 210m
                        },
                        new
                        {
                            Id = "67a30e2e-142b-4f9a-8319-85dc6e35eda4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "5b461",
                            ProductPrice = 220m
                        },
                        new
                        {
                            Id = "e09d45d6-e6f4-4372-9948-e36bc18f6332",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "e4c3a",
                            ProductPrice = 230m
                        },
                        new
                        {
                            Id = "699f6da0-5634-4891-9590-cff75863dbb5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "933af",
                            ProductPrice = 240m
                        },
                        new
                        {
                            Id = "8a4a88b0-0cdd-4ee8-8a55-37d9a716d383",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "52695",
                            ProductPrice = 250m
                        },
                        new
                        {
                            Id = "beddd616-d73d-43d2-b442-64b1e0f2170e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "befcd",
                            ProductPrice = 260m
                        },
                        new
                        {
                            Id = "73256b55-ec1f-42a3-9b72-bb482f3f3b23",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "80598",
                            ProductPrice = 270m
                        },
                        new
                        {
                            Id = "34ba8422-08b1-4fed-943c-31d080a2a1d9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "7bed6",
                            ProductPrice = 280m
                        },
                        new
                        {
                            Id = "c835c6e4-5dad-4166-9245-4d77dcb05dad",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "d7311",
                            ProductPrice = 290m
                        },
                        new
                        {
                            Id = "94c07f8c-f5b4-45d3-bf93-7ee72fc933f5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "52404",
                            ProductPrice = 300m
                        },
                        new
                        {
                            Id = "f0af55a0-ef13-438f-89bb-bca88b8b2aac",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "f1349",
                            ProductPrice = 310m
                        },
                        new
                        {
                            Id = "1d209a79-c538-4631-a06c-92167b96e04a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "150d8",
                            ProductPrice = 320m
                        },
                        new
                        {
                            Id = "4ddc2010-03cf-4ebf-80f7-ef3f9c92819d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "e1a3c",
                            ProductPrice = 330m
                        },
                        new
                        {
                            Id = "47709512-7e79-466c-9d30-25a25bc0728d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "1232f",
                            ProductPrice = 340m
                        },
                        new
                        {
                            Id = "1cf7e17d-beef-43e7-86ed-f79bdc7ba07e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "160d1",
                            ProductPrice = 350m
                        },
                        new
                        {
                            Id = "48ddb187-4349-4833-9a38-3f66b7ca64a3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "73a1e",
                            ProductPrice = 360m
                        },
                        new
                        {
                            Id = "31b946c5-fc1e-482a-a55f-0d2a9f2046a4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "917e6",
                            ProductPrice = 370m
                        },
                        new
                        {
                            Id = "7fc6506e-3a51-4399-a9b5-56dfbd158df2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "651bb",
                            ProductPrice = 380m
                        },
                        new
                        {
                            Id = "befd0ba9-e08a-4375-b998-ae3b51968ae0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "2e5a6",
                            ProductPrice = 390m
                        },
                        new
                        {
                            Id = "9263e346-7ae4-487a-93bf-cbe5cb9c1955",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "ccaf2",
                            ProductPrice = 400m
                        },
                        new
                        {
                            Id = "59df24f4-8d19-4002-9230-6407ab62645f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "3908a",
                            ProductPrice = 410m
                        },
                        new
                        {
                            Id = "b664742e-556c-4818-83ff-4279d214de5b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "c2bda",
                            ProductPrice = 420m
                        },
                        new
                        {
                            Id = "9a1a978d-5dc5-4d79-8486-ad42d8bad805",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "0043f",
                            ProductPrice = 430m
                        },
                        new
                        {
                            Id = "19a912c0-05a5-410f-86e5-9f9e45de9452",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "2d0b4",
                            ProductPrice = 440m
                        },
                        new
                        {
                            Id = "814389e4-496e-4942-b9a8-ff5f63316794",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "8edae",
                            ProductPrice = 450m
                        },
                        new
                        {
                            Id = "f0360ae8-eccf-49b0-b402-1324b66cf1a9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "b7da9",
                            ProductPrice = 460m
                        },
                        new
                        {
                            Id = "4981aec0-6827-453b-b07a-3bec25ac1e9f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "7f285",
                            ProductPrice = 470m
                        },
                        new
                        {
                            Id = "f2a8db92-2a82-479c-8ef1-130009871d50",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "af325",
                            ProductPrice = 480m
                        },
                        new
                        {
                            Id = "086a240b-2b77-4f2f-b90f-a863b08d07a2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "cbafc",
                            ProductPrice = 490m
                        },
                        new
                        {
                            Id = "ad9226a1-a89a-4c99-aa0e-f5558e9586b0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "e05d0",
                            ProductPrice = 500m
                        },
                        new
                        {
                            Id = "5ea6d3e5-92de-454f-9e02-b704e90fccb4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "0f200",
                            ProductPrice = 510m
                        },
                        new
                        {
                            Id = "a6fc3663-4ffa-4f27-ac11-86ec1b4bcac3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "8833a",
                            ProductPrice = 520m
                        },
                        new
                        {
                            Id = "e8211936-7590-469d-a8b3-5e48c77311f5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "51e3a",
                            ProductPrice = 530m
                        },
                        new
                        {
                            Id = "82459e6f-5362-4c42-9748-2d000617477f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "45580",
                            ProductPrice = 540m
                        },
                        new
                        {
                            Id = "d288132a-b322-4532-a567-13f750e69400",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "0225b",
                            ProductPrice = 550m
                        },
                        new
                        {
                            Id = "8ca80082-c545-4c97-9714-23bfdbc5bee8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "a373c",
                            ProductPrice = 560m
                        },
                        new
                        {
                            Id = "343e7b97-d807-4917-ba18-a85aed98fa4f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "86ca6",
                            ProductPrice = 570m
                        },
                        new
                        {
                            Id = "b0bc2cbc-b19e-4159-badc-58c85581f56f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "30295",
                            ProductPrice = 580m
                        },
                        new
                        {
                            Id = "5a28f69b-3bfd-4189-9582-105612f8ec3b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "a5d5b",
                            ProductPrice = 590m
                        },
                        new
                        {
                            Id = "73d34d35-0cf5-4e03-a666-f7202136749c",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "112b7",
                            ProductPrice = 600m
                        },
                        new
                        {
                            Id = "a9ef0eb7-316c-4ccf-9c68-a8535e551c27",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "24f1f",
                            ProductPrice = 610m
                        },
                        new
                        {
                            Id = "da3bb9ed-6d90-4bfc-be5c-3400cbf158c2",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "e0bd0",
                            ProductPrice = 620m
                        },
                        new
                        {
                            Id = "18a0ff1a-53f0-4848-bed3-3deb689bff98",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "76063",
                            ProductPrice = 630m
                        },
                        new
                        {
                            Id = "fe3fe276-c381-4a61-8bd1-d967a1d8f71b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "ab6cd",
                            ProductPrice = 640m
                        },
                        new
                        {
                            Id = "128e11b4-69c2-4859-be41-46354205b50a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "8d18d",
                            ProductPrice = 650m
                        },
                        new
                        {
                            Id = "4c7b5672-615b-4460-b24b-975f6cbb2361",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "d8c75",
                            ProductPrice = 660m
                        },
                        new
                        {
                            Id = "cd9ea38f-940a-415a-b9ec-e93e0f68ea06",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "8a486",
                            ProductPrice = 670m
                        },
                        new
                        {
                            Id = "a3fdf44a-6567-4177-a66f-429bf7514684",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "f06c5",
                            ProductPrice = 680m
                        },
                        new
                        {
                            Id = "109e4626-b78d-407e-b7bc-7bd1da13b01d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "cce7c",
                            ProductPrice = 690m
                        },
                        new
                        {
                            Id = "dfa341a1-7dfe-409d-951c-0c3cf286f053",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "2fa6f",
                            ProductPrice = 700m
                        },
                        new
                        {
                            Id = "4c5b4522-c4fc-429e-a076-87a0eb6ebddd",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "1e370",
                            ProductPrice = 710m
                        },
                        new
                        {
                            Id = "16cfc5cc-d83d-4821-ae17-5b0afb8acd6b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "667eb",
                            ProductPrice = 720m
                        },
                        new
                        {
                            Id = "3193a9bd-3286-46b4-b47f-00cf30f0c469",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "6f2da",
                            ProductPrice = 730m
                        },
                        new
                        {
                            Id = "467f0265-2b17-4f41-b9e6-60ce78943ac3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "d57f1",
                            ProductPrice = 740m
                        },
                        new
                        {
                            Id = "a0e24735-be12-40e9-86a1-3862a4ff553c",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "0dd09",
                            ProductPrice = 750m
                        },
                        new
                        {
                            Id = "069c661d-7c54-4792-8918-1085d11a52e0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "4e8be",
                            ProductPrice = 760m
                        },
                        new
                        {
                            Id = "e564452e-d638-42ed-92d7-8cb94669bffc",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "de25b",
                            ProductPrice = 770m
                        },
                        new
                        {
                            Id = "c83ae27d-a4ca-447c-bff7-ea302c9cb3b5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "85ed1",
                            ProductPrice = 780m
                        },
                        new
                        {
                            Id = "25da2764-74d9-47ac-8060-8fbe138157fa",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "77ba1",
                            ProductPrice = 790m
                        },
                        new
                        {
                            Id = "217e7127-b6dc-4aac-b7cb-65988382fb16",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "62185",
                            ProductPrice = 800m
                        },
                        new
                        {
                            Id = "d3632671-5b45-4d30-84be-5791c4ea09a8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "c6a12",
                            ProductPrice = 810m
                        },
                        new
                        {
                            Id = "e9124a4e-6292-46a3-90d7-6b44573b1f65",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "63f8d",
                            ProductPrice = 820m
                        },
                        new
                        {
                            Id = "88da2ead-44a9-460b-8620-98f9136bcb41",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "345f2",
                            ProductPrice = 830m
                        },
                        new
                        {
                            Id = "bf577890-57a6-4eeb-a124-2ddce9c43ff3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "4276b",
                            ProductPrice = 840m
                        },
                        new
                        {
                            Id = "93ee59c5-b119-4baf-9700-864503938ef5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "e764f",
                            ProductPrice = 850m
                        },
                        new
                        {
                            Id = "81cbfc68-4416-4394-955e-0fbc8bfed246",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "3c604",
                            ProductPrice = 860m
                        },
                        new
                        {
                            Id = "aeeb5ac5-fe36-48d0-bbb6-7dd2f87692bf",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "12c2d",
                            ProductPrice = 870m
                        },
                        new
                        {
                            Id = "ee06a191-e85c-4920-946a-86f854bb3b5e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "5953f",
                            ProductPrice = 880m
                        },
                        new
                        {
                            Id = "c0bad910-2b72-4b0d-85bd-bb6fc98bb778",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "b0c73",
                            ProductPrice = 890m
                        },
                        new
                        {
                            Id = "3d8c289d-b96b-42c5-a5c0-d00e58da4ad3",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "80c59",
                            ProductPrice = 900m
                        },
                        new
                        {
                            Id = "51e09222-c6d6-44b7-aca5-94b9e3399093",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "9323f",
                            ProductPrice = 910m
                        },
                        new
                        {
                            Id = "70a50f39-dfd8-49e1-9c13-56f7cc9abae8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "6a418",
                            ProductPrice = 920m
                        },
                        new
                        {
                            Id = "43cb7890-fe76-4a50-b571-5a8be53f5d72",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "61ee6",
                            ProductPrice = 930m
                        },
                        new
                        {
                            Id = "6f573a3d-c34e-4d59-a4f3-dccbba65dc68",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "973c3",
                            ProductPrice = 940m
                        },
                        new
                        {
                            Id = "1aa29566-8101-45a4-adae-f451ba50adad",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "e7733",
                            ProductPrice = 950m
                        },
                        new
                        {
                            Id = "1e16913f-6364-49d1-a1d6-8478a7218265",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "4cb4b",
                            ProductPrice = 960m
                        },
                        new
                        {
                            Id = "aae71e32-a999-4660-8261-2a0cebac1930",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "a3e30",
                            ProductPrice = 970m
                        },
                        new
                        {
                            Id = "7eeb63f1-3bc7-482a-9635-01f2982a9f65",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "69880",
                            ProductPrice = 980m
                        },
                        new
                        {
                            Id = "23fb0efd-0eac-4e41-81c4-649aaca562e9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentCountInWarehouse = 100,
                            MinimumCountAlert = 10,
                            ProductName = "aa237",
                            ProductPrice = 990m
                        });
                });

            modelBuilder.Entity("Data.Models.Models.Seller", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SellerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = "490c3618-f34d-4972-a830-faa7007cc6f0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerNumber = "1",
                            UserId = "929a9893-27af-4f68-8dbd-574ed0ced1ce"
                        },
                        new
                        {
                            Id = "01004ba9-2ff3-4805-87b6-3ec01b8955e4",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerNumber = "1",
                            UserId = "9cb16286-4fc4-4272-8449-f53347bb2926"
                        },
                        new
                        {
                            Id = "4de91f94-c521-4274-9c5e-c62e0154461e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerNumber = "1",
                            UserId = "21c6fd77-0b9d-4ce1-85d1-9e8ef6eba4cf"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.SellerCustomer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("SellerCustomers");
                });

            modelBuilder.Entity("Data.Models.Models.SellerProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SellerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("SellerProduct");

                    b.HasData(
                        new
                        {
                            Id = "cf9c989a-3a63-4e7b-b2a7-ee4a75ba8f01",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "79991602-1a2d-4802-8382-49f06fe414ef",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        },
                        new
                        {
                            Id = "2e304bab-31f6-490d-a66c-434bd027956a",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "79991602-1a2d-4802-8382-49f06fe414ef",
                            SellerId = "490c3618-f34d-4972-a830-faa7007cc6f0"
                        },
                        new
                        {
                            Id = "4fcfbdd0-b88f-469c-8851-c58c02407e96",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "c32459d5-cb0a-410c-abf3-1129dc40c4be",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        },
                        new
                        {
                            Id = "57e4fc6a-0e24-4fef-a061-8b361f014981",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "370190e4-cf7b-4cb9-a5f8-e94ce111339a",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        },
                        new
                        {
                            Id = "b9a34c27-f879-468e-bed6-b75951077d27",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "55a010fd-d9aa-4152-b474-71434c259a9f",
                            SellerId = "490c3618-f34d-4972-a830-faa7007cc6f0"
                        },
                        new
                        {
                            Id = "824e9fc8-ef6d-4952-a9a3-a02e1acbc2c0",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "b0836acc-acd3-4408-8af7-c1fe85ff3fcf",
                            SellerId = "490c3618-f34d-4972-a830-faa7007cc6f0"
                        },
                        new
                        {
                            Id = "bd2951f9-5211-4f25-b887-e47f21b0891f",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "95b059b5-9341-4b63-975e-0be2116ec68a",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        },
                        new
                        {
                            Id = "15f6dbd2-227e-48b3-aafc-ed998db81f83",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "35afa419-73f9-41c1-9f4f-7c86e88b62c8",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        },
                        new
                        {
                            Id = "f7f26f1c-4f35-4a13-b974-29c766bcc697",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "03a70466-dc82-427d-97f0-38a4ba09cbde",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        },
                        new
                        {
                            Id = "7877a5ec-5bbc-45d2-afed-cf4a4d8ca8f5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = "95b059b5-9341-4b63-975e-0be2116ec68a",
                            SellerId = "01004ba9-2ff3-4805-87b6-3ec01b8955e4"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "929a9893-27af-4f68-8dbd-574ed0ced1ce",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            UserName = "Minka"
                        },
                        new
                        {
                            Id = "9cb16286-4fc4-4272-8449-f53347bb2926",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            UserName = "Ginka"
                        },
                        new
                        {
                            Id = "21c6fd77-0b9d-4ce1-85d1-9e8ef6eba4cf",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            UserName = "Gosho"
                        });
                });

            modelBuilder.Entity("Data.Models.Models.Customer", b =>
                {
                    b.HasOne("Data.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.Models.Models.Image", b =>
                {
                    b.HasOne("Data.Models.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Data.Models.Models.Seller", b =>
                {
                    b.HasOne("Data.Models.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.Models.Models.SellerCustomer", b =>
                {
                    b.HasOne("Data.Models.Models.Customer", "Customer")
                        .WithMany("SellerCustomers")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Data.Models.Models.Product", null)
                        .WithMany("SellerCustomers")
                        .HasForeignKey("ProductId");

                    b.HasOne("Data.Models.Models.Seller", "Seller")
                        .WithMany("SellerCustomers")
                        .HasForeignKey("SellerId");
                });

            modelBuilder.Entity("Data.Models.Models.SellerProduct", b =>
                {
                    b.HasOne("Data.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Data.Models.Models.Seller", "Seller")
                        .WithMany("SellerProducts")
                        .HasForeignKey("SellerId");
                });
#pragma warning restore 612, 618
        }
    }
}
